// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inlhoymxrlekspioxmmo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlubGhveW14cmxla3NwaW94bW1vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMzk2NTQsImV4cCI6MjA2MjgxNTY1NH0.5P7WgW3o2V5jLf6qZBzSJGErfVIntIgcmlwMP9mnnLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);